### ISSUE TITLE
What Gradle configuration should I use to configure a Hikari DataSource?

### ISSUE THREAD

**Issue by martinanderssondotcom** [micronaut-projects/micronaut-sql#120]
[This page][1] says `runtime`. [Other page][2] says `implementation`.

It would be great if the documentation could be consistent, and also explain the "why".

In my use case, I needed to be absolutely sure what connection pool ended up being used in my Micronaut app in order to make programmatic assumptions related to thread-safety and the reuse of jOOQ queries. What follows is my little experiment trying to figure out what difference one configuration has versus the other.

## Gradle gist

The Java plugin's `compile` and `runtime` configurations got deprecated and replaced by `implementation` and `runtimeOnly` (see [this][3] and [that][4]). The Java Library plugin makes a further distinction between implementation and `api`, the distinction between these two being should stuff be available without (= "implementation") or with (= "api") transitive dependencies (see [this][5]).

Given that we are writing Micronaut _applications_ (and not libraries) we should only have to chose between `implementation` and `runtimeOnly` - i.e., we can skip `api`.

The Micronaut docs referenced above sort of mix both the old and the new, so we need to figure out the difference between three of these configurations: `implementation`, `runtime` (deprecated) and `runtimeOnly`. Heck, I'll throw in `compileOnly` for the fun of it.

## Running the app

Research question: What datasource implementation do we see using different Hikari configurations?

Method: I declared a controller which got a `javax.sql.DataSource` injected. In my current project, I had to cast this guy to a `org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy` and use method `getTargetDataSource()` to unwrap the real datasource. I run the app using `gradle run`.

- `implementation`: SQL queries work, implementation class is `io.micronaut.configuration.jdbc.hikari.HikariUrlDataSource`.
- `runtime`: same as `implementation`.
- `runtimeOnly`: same as `implementation`.
- `compileOnly`: The request hangs, no error log no nothing (!).

## Building the app

Gradle is a little bit of a .. erm [mess][6]. So this is where things become really exiting. Given configuration X or Y, what are the implications for my built artifact, the one I intend to distribute or run in production?

The current project I'm working on builds an uber jar with all classes exploded into the singleton JAR archive (not my choice lol) using [this plugin][7]. I noticed two differences.

Configurations `implementation` and `runtime` included in the built jar packages `io.micronaut.configuration.jdbc.hikari` and `com.zaxxer.hikari`.

However, configurations `runtimeOnly` and `compileOnly` only included package `com.zaxxer.hikari`.

## Conclusions

For my Gradle run command, I would like to use `implementation`. This basically says; "hey we better have the Hikari thing available during compile-time since Micronaut adds all his magic during compilation, plus, implementation also includes runtime and it's probably a good idea to have Hikari available then as well".

But a peculiar question arise: Why did `runtimeOnly` work just fine?? I would have thought `runtimeOnly` meant Micronaut didn't notice Hikari during compile-time!

The build command had a different effect. For the build, the `runtimeOnly` made Micronaut not include his Hikari-specific configuration and I can only assume - not tested - that the built jar wouldn't actually run or fallback to some other weird datasource type.

As `runtime` is deprecated, this pretty much leave us with `implementation` as the only option for the build.

**So to summarize**, `implementation` is what I have to go with in order to get the best out of both Gradle commands.

Anyways, would be super cool if you clarify all this since your framework is mostly "compile-time" magic and as it stands right now, the documentation is not consistent. I would appreciate your feedback very much!

[1]: https://micronaut-projects.github.io/micronaut-sql/latest/guide/#_configuring_a_jdbc_datasource

[2]: https://guides.micronaut.io/micronaut-data-access-jpa-hibernate/guide/index.html#_data_source_configuration

[3]: https://docs.gradle.org/current/userguide/java_plugin.html#tab:configurations

[4]: https://docs.gradle.org/current/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations

[5]: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

[6]: https://discuss.gradle.org/t/what-is-the-difference-between-5-different-java-related-plugins/31953

[7]: https://github.com/johnrengelman/shadow

**Comment by graemerocher** [comment]
So we are still in the process of migrating all the docs to Gradle's new non-deprecated scope names (`implementation`, `testImplementation` etc.). See commit https://github.com/micronaut-projects/micronaut-docs/commit/34466598a940af9163ee56e3512ddfcd062aa867 from 6 days ago

If there is something we can agree on that yes Gradle is a bit of a mess in this regard. 

The reason `runtimeOnly` worked fine is because Micronaut has already enhanced the classes of that library and doesn't need to do so again for each user project. 

Makes sense to me that `compileOnly` didn't work since that removes the dependency from the runtime classpath.

I am not sure what the statement "The build command had a different effect" means.

Maybe we do need a section in the docs that explains Gradle scopes and how they relate to Micronaut, although if we did that we would need to do the same for Maven as Micronaut is build tool agnostic at this stage.

**Comment by martinanderssondotcom** [comment]
I was hoping that the paragraph after "the build command had a different effect" explained the effect. What I meant is, in other words, this:

`runtimeOnly` worked fine for `gradle run` but the same configuration did not work for `gradle build` as classes in package `io.micronaut.configuration.jdbc.hikari` was not included with the built jar, which they were when I used `implementation` and `runtime`.

But then, I never tried to run the jar. I make the assumption that classes in `io.micronaut.configuration.jdbc.hikari` is necessary to be on the classpath in order for the app to use a Hikari connection pool. Why otherwise would `implementation` and `runtime` include them?

So, this is what I mean is "the difference". With `runtimeOnly` we can run the app using Gradle, but we can't build a runnable jar (at least not with the same semantics - I assume).

I do not understand your comment on `runtimeOnly`. But then, I keep thinking of Micronaut as "mostly" compile-time magic. So if I didn't have the Hikari classes on the classpath while compiling, how come - as you seem to be saying - things got "enhanced" anyways? Further, I actually didn't think Micronaut did anything with my classes. I was under the impression Micronaut only add generated code, which has a composing dependency on my classes but otherwise, the bytecode of my classes remain completely unchanged and Micronaut doesn't even proxy or subclass my classes?

Anyways, here we go down the rabbit hole lol. Yes, docs, please!! I know a thing or two about Gradle, and I know a thing or two about Micronaut. But then, I need to merge these two rather complex entities and I can only guess what will happen or what semantics will apply.

I think that a whole section/chapter on "how Micronaut works"; when does Micronaut do what during compile-time and when does Micronaut do what during runtime tied-in with Gradle's configurations would be a dream come true.

I didn't expect `compileOnly` to work. But then, I didn't expect `runtimeOnly` to work either. So at this point I give up lol.

Thank you so much for being helpful! =) On my end I will go with "implementation" and stop asking questions hahahaha
