### ISSUE TITLE
IllegalAccessError when using jOOQ with Micronaut 4.4.1

### ISSUE THREAD

**Issue by davidsonnabend** [micronaut-projects/micronaut-sql#1324]
### Expected Behavior

Our application uses jOOQ next to micronaut-data to execute specific queries.

After updating  from Micronaut 4.3.3 to Micronaut 4.4.1 the application won't start anymore due to an `IllegalAccessError`.

As soon as the `DSLContext` is injected into a repository or service and used to execute queries, the application stops working. It is not necessary to execute the query at all.

Detailed error message (of the attached example application):

```
Message: Failed to load a service: java.lang.IllegalAccessError: failed to access class org.jooq.impl.AbstractRow from class com.example.jooq.generated.tables.records.$PersonRecord$Introspection (org.jooq.impl.AbstractRow and com.example.jooq.generated.tables.records.$PersonRecord$Introspection are in unnamed module of loader 'app')
Path Taken: new SchemaGenerator(List configurations,JdbcSchemaHandler schemaHandler)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1982)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:294)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3348)
        at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3692)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:342)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:202)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:74)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:328)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:303)
        at com.example.ApplicationKt.main(Application.kt:5)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.data.jdbc.config.SchemaGenerator]
```

### Actual Behaviour

jOOQ could be used (within `JdbcRepository`) without any error like in previous Micronaut versions.

### Steps To Reproduce

1. Clone example application
2. Run `./gradlew test` or `./gradlew run`

### Environment Information

- Operating System: Ubuntu 23.10
- JDK Version: 21.0.1-zulu

### Example Application

https://github.com/davidsonnabend/micronaut-illegal-access-error

### Version

4.4.1

**Comment by timyates** [comment]
Investigating...  I see the failure in the reproducer -- however it also seems to fail for Micronaut 4.3.3  🤔

**Comment by timyates** [comment]
I guess it might be a different version of the org.jooq.jooq-codegen-gradle plugin 🤔

**Comment by timyates** [comment]
@davidsonnabend Do you use this same jooq plugin in your pre-migrated version that works?

**Comment by davidsonnabend** [comment]
Our current working project uses Micronaut 4.3.3 with `org.jooq.jooq-codegen-gradle` plugin version `3.19.4`. 

I updated the jOOQ plugin to match the used jOOQ version of Micronaut 4.4.x .

**Comment by timyates** [comment]
Cool, thanks for the info!  Trying to see why changing `micronautVersion` to 4.3.3 and the codegen plugin to `3.19.4` in the reproducer doesn't make it work 🤔 Does it work for you?

Are you re-generating the jooq files?

Are they different between working and non-working?  Ie: does `PersonRecord` change?

**Comment by davidsonnabend** [comment]
> Cool, thanks for the info! Trying to see why changing `micronautVersion` to 4.3.3 and the codegen plugin to `3.19.4` in the reproducer doesn't make it work 🤔 Does it work for you?

I also can't make the reproduces work by rolling it back to Micronaut 4.3.3 and jOOQ 3.19.4. 🤯

> Are you re-generating the jooq files?

Yes.

> Are they different between working and non-working? Ie: does `PersonRecord` change?

No.

I will dig deeper into this and try to create a working example application using the Micronaut 4.3.3. .
This will hopefully give us more information.

**Comment by timyates** [comment]
> I will dig deeper into this and try to create a working example application using the Micronaut 4.3.3. .

Awesome, thank you 👍

**Comment by davidsonnabend** [comment]
I was able to get the example application running with Micronaut 4.3.3 and jOOQ 3.19.4.

With `datasources.default.schema-generate: NONE` the reproducer works with Micronaut 4.3.3 and jOOQ 3.19.4. (I manually created a the database)

As soon as I change the settings to `schema-generate: CREATE_DROP` the app stops working in 4.3.3 too.

Using Mirconaut 4.4.1. the application crashes with both settings. 

The updated example application works for me when I downgrade it to Micronaut 4.3.3.

**Comment by timyates** [comment]
Awesome, thank you! I will investigate 👍

**Comment by sdelamo** [comment]
Please, note that  you should not rely on `datasources.default.schema-generate` to generate your schema. 

See https://micronaut-projects.github.io/micronaut-data/snapshot/guide/ :

> To create the database schema it is recommended you pair Micronaut Data with a SQL migration tool such as [Flyway](https://micronaut-projects.github.io/micronaut-flyway/snapshot/guide/index.html) or [Liquibase](https://micronaut-projects.github.io/micronaut-liquibase/snapshot/guide/index.html).

> SQL migration tools provide more complete support for creating and evolving your schema across a range of databases.

> **The schema-generate option is currently only recommended for simple applications, testing and demos and is not considered production-ready**.

**Comment by davidsonnabend** [comment]
> Please, note that you should not rely on `datasources.default.schema-generate` to generate your schema.

I know. 😀 This was only used for the demo application for the sake of simplicity.

**Comment by timyates** [comment]
I *think* https://github.com/micronaut-projects/micronaut-core/pull/10777 fixes this...

**Comment by timyates** [comment]
Will be finxed by https://github.com/micronaut-projects/micronaut-core/pull/10777 in Micronaut 4.4.2
