### ISSUE TITLE
JOOQ - GraalVM native image compatibility

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-sql#151]
JOOQ can be made native image compatible, see:

https://github.com/jOOQ/jOOQ/issues/8779#issuecomment-616177481
https://github.com/jOOQ/jOOQ/issues/8779#issuecomment-616182926

We can add this substitution to this repository to enable it for Micronaut users:

```java
@TargetClass(className = "org.jooq.impl.DefaultRecordMapper", innerClass = "ProxyMapper")
final class ProxyMapper_Substitute {
	@Substitute
	private Object proxy() {
		throw new UnsupportedOperationException("Can't work with GraalVM native");
	}
}
```

And add comment based on this to documentation:

> the dependency javax.persistence-api was indeed needed for the build to happen without problem (an alternative could be to use the native-image option --allow-incomplete-classpath)

**Comment by graemerocher** [comment]
Good idea, want to send a PR?

**Comment by morki** [comment]
@graemerocher yes, but it will take same time, I have another problems with basic type mapping, need to investigate.

**Comment by morki** [comment]
@graemerocher another question:

When using `@Introspected` annotation to enable reflection, there is `packages` option, which is ideal for JOOQ generated packages with `Record`s, but it force you to use `includedAnnotations` property, which is not ideal in this case. Is there a workaround to introspect whole package without using this property?

**Comment by graemerocher** [comment]
Not currently no. Allowing any type to be introspected is unlikely to work well

**Comment by morki** [comment]
@graemerocher sorry, I thought `@TypeHint` annotation. However I have working solution, but i don't like it being explicit about listing all your `Record` classes. Do you see here some alternative, like introducing something like `@TypeHint(packages={"my.package"})`?

1) ProxyMapper substitution:

```java
import com.oracle.svm.core.annotate.Substitute;
import com.oracle.svm.core.annotate.TargetClass;

@TargetClass(className = "org.jooq.impl.DefaultRecordMapper", innerClass = {"ProxyMapper"})
final class ProxyMapperSubstitute {
    @Substitute
    private Object proxy() {
        throw new UnsupportedOperationException("Can't work with GraalVM native");
    }
}
```

2) DefaultDataType reflection configuration:

```java
import io.micronaut.core.annotation.TypeHint;
import io.micronaut.core.annotation.TypeHint.AccessType;
import org.jooq.JSON;
import org.jooq.JSONB;
import org.jooq.Result;
import org.jooq.RowId;
import org.jooq.types.*;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Timestamp;
import java.time.*;

@TypeHint(accessType = {AccessType.ALL_PUBLIC_CONSTRUCTORS}, value = {
        LocalDate[].class,
        LocalDateTime[].class,
        LocalTime[].class,
        ZonedDateTime[].class,
        OffsetDateTime[].class,
        OffsetTime[].class,
        Instant[].class,
        Timestamp[].class,
        BigInteger[].class,
        BigDecimal[].class,
        UNumber[].class,
        UByte[].class,
        UInteger[].class,
        ULong[].class,
        Unsigned[].class,
        UShort[].class,
        YearToMonth[].class,
        YearToSecond[].class,
        RowId[].class,
        Result[].class,
        JSON[].class,
        JSONB[].class
})
final class DefaultDataTypeHints {

}
```

3) Native image instrumentation:

```
Args = -H:ClassInitialization=org.jooq.SQLDialect$ThirdParty:build_time \
       --initialize-at-run-time=io.micronaut.configuration.jooq.spring.SpringTransactionProvider
```

4) Manualy define custom `Record` clases in `@TypeHint` annotation:

```java
@TypeHint(value = {
    MyTableRecord.class,
    OtherTableRecord.class
})
class RecordTypeHints {

}
```

**Comment by graemerocher** [comment]
@morki what I would do is add a `@Subsitute` method for `ImmutablePOJOMapper.map` that uses `io.micronaut.core.reflect.InstantiationUtils.instantiate` instead of reflection directly to crew new instances and then you could annotated your record classes with `@Introspected` and it would just work

**Comment by graemerocher** [comment]
`@Introspected` also supports `packages` so you could define a whole package of them etc.

**Comment by morki** [comment]
@graemerocher thank you very much, I will try to go this way, but there is the same problem with `@Introspected(packages={ ... })`, because it needs some annotation on the `Record` classes and they are generated by JOOQ.

**Comment by morki** [comment]
@graemerocher maybe I misunderstood your point, I am new to Java, so sorry for maybe dumb questions...

**Comment by graemerocher** [comment]
No you are correct that `@Introspected` currently requires an annotation. So we may need something else although I am unsure what that should be at this stage.

**Comment by morki** [comment]
@graemerocher thank you, so would you like me to contribute the previous changes and for now, documenting that all `Record` classes need to be added to `@TypeHint` annotation for now?

**Comment by morki** [comment]
@graemerocher I found some way to do this: https://www.jooq.org/doc/3.12/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-annotations/

JOOQ can generate `@Generated` annotation and with that, we can use `@Introspected(packages={"package.of.your.records"})` and you `ImmutablePOJOMapper.map` substitution with `InstantiationUtils.instantiate`.

What do you think?

**Comment by graemerocher** [comment]
Seems like a great idea

**Comment by morki** [comment]
@graemerocher After some prototyping, I think the idea with `@Generated` annotation is not good. 

As of this comment https://github.com/jOOQ/jOOQ/issues/8779#issuecomment-567492457 JOOQ author is intended to provide native image compatibility in long run, so maybe we can just help our users (and me :)) to use basic functionality now in native image, and wait for JOOQs native solution.

I created PR https://github.com/micronaut-projects/micronaut-sql/pull/177 with that solution.

Thank you for feedback.

**Comment by ilopmar** [comment]
@morki could you please share a Micronaut application that uses JOOQ so I can use it as a base app for our Micronaut-GraalVM CI?
I don't have experience with JOOQ so I'd really appreaciate if you can share a simple app like this https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/master_h2. It only contains a few domain classes and some db queries.
Thanks!

**Comment by morki** [comment]
@ilopmar yes, I will try. Can I see the CI code somewhere? It seems it's not using Github Actions.

**Comment by ilopmar** [comment]
@morki Sorry but I didn't explain properly. You don't need to worry about CI, that's my job. What I would like is a Micronaut JOOQ application (written in Java) with a couple of entities and queries configured as a native-image and that I can also run with `./gradlew run`.
Then I can adapt it and make part of our CI pipeline.

Also, depending on how the app and the GraalVM configuration look like, maybe we can improve the support generating the metainformation needed with our GraalTypeElementVisitor or writing a GraalVM AutomaticFeature. But to do it, first I need a running app so I can take a look and understand how JOOQ works.

If you are curious, this is the Micronaut Data JDBC test application we use for testing GraalVM integration: https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal
And this is the CI pipeline (we use Gitlab CI for that): https://gitlab.com/micronaut-projects/micronaut-graal-tests/pipelines

**Comment by morki** [comment]
@ilopmar Hi, I have something here https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/pull/1 so let's move this discussion there :)

**Comment by ilopmar** [comment]
@morki What is happening is a bug in Micronaut not generating the right introspection metadata for array classes. See https://github.com/micronaut-projects/micronaut-core/issues/3481

I'm going to move all those classes from `value` parameter to `typeNames` as explained in the workaround.
