### ISSUE TITLE
Could not find io.micronaut.configuration:micronaut-vertx-pg-client

### ISSUE THREAD

**Issue by BenStuart** [micronaut-projects/micronaut-sql#164]
Followed instructions here:
https://micronaut-projects.github.io/micronaut-sql/latest/guide/index.html#vertxpgclient

Added: 
` implementation("io.micronaut.configuration:micronaut-vertx-pg-client")` to my `build.gradle`, imported changes to `build.gradle` using IntelliJ

Attempted:
 `./gradlew run`

Got:
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find io.micronaut.configuration:micronaut-vertx-pg-client:.
     Required by:
         project :
```

**Comment by BenStuart** [comment]
While I am here, in that example the `application.yml` indenting is all out of wack.

I assume its:
```
#  vertx:
#    pg:
#      client:
#        port: 5432
#        host: localhost
#        database: iandwdb
#        user: postgres
#        password: mysecretpassword
#        maxSize: 5
```

**Comment by goeh** [comment]
Same problem here. I tried to upgrade a project from Micronaut 1.2.11 to 1.3.5 and replaced `micronaut-postgres-reactive` with `micronaut-vertx-pg-client`. Got the above error message. So I created a new project from scratch with `mn create-app my-app --features vertx-pg-client`. Same error.

**Comment by goeh** [comment]
Artifact seems to be missing from the bom. Specifying a version number solved the problem `implementation "io.micronaut.configuration:micronaut-vertx-pg-client:1.4.0"`
