### ISSUE TITLE
Default physical naming strategy for Hibernate JPA

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [micronaut-projects/micronaut-sql#17]
Hello!

When using Hibernate JPA the schema validation tries to match the table name using exactly the same name as the entity. So a entity called `FooBar` must exists as a `FooBar` table in the database. This behavior can be changed by creating a custom naming strategy and set it to hibernate.

On Predator JDBC this is the current strategy:

> The default naming strategy when converting camel case class and property names to database tables and columns is to use underscore separated lower case. In other words FooBar becomes foo_bar.

Would be possible to make this strategy the default strategy for JPA as well, just like Spring JPA does?

Best regards,
Rafael Pacheco.

**Comment by graemerocher** [comment]
probably a good idea. Not sure it can be done without incrementing the major version

**Comment by rafaelrenanpacheco** [comment]
In the 1.* version this could be opt-in with some new property, like:
- sql.physical-naming-strategy=snakecase

In the 2.* version this would be the default, so no property is required for those who want to use the snake case naming strategy. If the user want to go back to the 1.* behavior then the property would be something like this:
- sql.physical-naming-strategy=pascalcase

(the property name and values are just for explanation purposes)

**Comment by graemerocher** [comment]
I think we can probably set the default to under score separated for Micronaut Data JPA since that is unreleased software and would result in a non-breaking change. 

See https://github.com/micronaut-projects/micronaut-data/issues/103

**Comment by rafaelrenanpacheco** [comment]
Agreed, this feature request is indeed related to Micronaut Data JPA. Closing it in order to follow it on micronaut-projects/micronaut-data#103.
