### ISSUE TITLE
Can't install UCP

### ISSUE THREAD

**Issue by hrpath** [micronaut-projects/micronaut-sql#189]
Hello,

I'm trying to update my project from direct Oracle jar dependency to UCP

Blog post from Oracle differs from Micronaut documentation.
Not sure how to declare the dependencies, runtime or implementation
Not sure that UCP package is published looking at the error message

Thank you !

### Steps to Reproduce

1. Add dependencies to gradle
implementation('io.micronaut.configuration:micronaut-jdbc-ucp')

### Expected Behaviour

App compile

### Actual Behaviour

Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find io.micronaut.configuration:micronaut-jdbc-ucp:.
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by graemerocher** [comment]
It was only added to the BOM in newer versions of Micronaut 1.3.x
