### ISSUE TITLE
Release new patch version

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-sql#198]
Can we release new patch version with fix of JOOQ GraalVM please?

**Comment by ilopmar** [comment]
Sure!

**Comment by ilopmar** [comment]
Relase published (waiting for sync to Central). Also PR for updating the BOM created. I'll merge it once the build passes.

For future requests like this is better if you ask directly on our Gitter channel: https://gitter.im/micronautfw/

**Comment by morki** [comment]
Thank you very much @ilopmar, next time I will use Gitter :)
