### ISSUE TITLE
JASYNC dependency is not managed by micronaut-sql

### ISSUE THREAD

**Issue by LPalmerMSI** [micronaut-projects/micronaut-sql#474]
Micronaut 2.5.7

The jasync version must be set manually in build.gradle because the dependency is not managed by micronaut-sql.

When build.gradle includes:
```
implementation ("com.github.jasync-sql:jasync-postgresql")
```
Then gradle error:
```
A problem occurred configuring root project 'nitro-nbi'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find com.github.jasync-sql:jasync-postgresql:
```

Workaround:
Look at gradle.properties in the main project directory and include the compatible version.  Add it to the import:
```
implementation ("com.github.jasync-sql:jasync-postgresql:1.1.4")

**Comment by graemerocher** [comment]
Fixed by new `micronaut-sql-bom` subproject
