### ISSUE TITLE
JOOQ causing runtime error with Micronaut framework when running on native image

### ISSUE THREAD

**Issue by arbbista** [micronaut-projects/micronaut-sql#509]
### Issue description

I have built a project with Micronaut framwork and JOOQ library for database connection that runs with GraalVM native-image. It works fine until I make a request which makes a connection to the database that uses JOOQ library.

This is the error that occurs:

```
14:11:34.486 [default-nioEventLoopGroup-1-3] INFO  o.s.j.support.SQLErrorCodesFactory - Default sql-error-codes.xml not found (should be included in spring-jdbc jar)
14:11:34.486 [default-nioEventLoopGroup-1-3] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Could not construct new record

....

Caused by: java.lang.NoSuchMethodException: com.smartbits.configurations.jooq.tables.records.UserConfigurationsRecord.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3349)
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
	at org.jooq.impl.Tools.recordFactory(Tools.java:900)
	... 171 common frames omitted
```
I am currently using JOOQ plugin:
```
nu.studer.jooq version '5.2'
```

and the dependency:
```
implementation("io.micronaut.sql:micronaut-jooq")
```

With GraalVM I have generated the JSON configurations that are needed for the native-image build which are not empty:
```
jni-config.json, reflect-config.json, resource-config.json
```

I want to know if there is a way to run JOOQ on a native-image and automatically generate configuration JSON files for JOOQ classes.

I've made some research and I have tried:
- To manually write reflection configurations for JOOQ (just to test it)
- To add `@Introspected` annotation on JOOQ models

As I noticed, the GraalVM doesn't recognize JOOQ classes to create reflection configurations for them.

Here's a cross post by me on stackoverflow:
https://stackoverflow.com/q/69940459/521799

**Comment by graemerocher** [comment]
You can annotate `UserConfigurationsRecord` with `@ReflectiveAccess` since JOOQ seems to require it

**Comment by arbbista** [comment]
> You can annotate `UserConfigurationsRecord` with `@ReflectiveAccess` since JOOQ seems to require it

Thank you for you answer Graeme but it's not working.

**Comment by arvidvillen** [comment]
I have a similar problem.
Adding `jpaAnnotations = true` (like the guide says https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jooq) does not work as JOOQ 3.16 generates Jakarta annotations (https://blog.jooq.org/jooq-3-16-and-java-ee-vs-jakarta-ee/) which seems to not be supported by Micronaut.
It would be awesome if Micronaut had native support for JOOQ (at least fix graalvm image). e.g. by a protpery like:

```
jooq:
  package: 'com.example.db.model'
```

**Comment by morki** [comment]
@arvidvillen, @arbbista Jakarta annotations are now supported by newest Micronaut versions and with these, it works like a charm. Can be closed.

**Comment by radovanradic** [comment]
Per last comment this can be closed.
