### ISSUE TITLE
JpaConfiguration::findEntities is using a non-thread safe HashSet

### ISSUE THREAD

**Issue by rawilder** [micronaut-projects/micronaut-sql#511]
### Expected Behavior

Multiple packages are scanned and all entities are recognized.

### Actual Behaviour

Not all entities are recognized when multiple packages are specified in entity-scan. 

I'm having a hard time validating without actually cloning and referencing a local copy version of the library, but from my understanding of HashSet, it is a non-thread safe data structure and the parallel stream being used might be an unsafe pairing. 

https://github.com/micronaut-projects/micronaut-sql/blob/3.1.x/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java#L284

https://github.com/micronaut-projects/micronaut-core/blob/3.1.x/core/src/main/java/io/micronaut/core/io/scan/AnnotationScanner.java#L136

From the [javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html#forEach(java.util.function.Consumer)) of `Stream::forEach` (which is used [here](https://github.com/micronaut-projects/micronaut-sql/blob/3.1.x/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java#L288))

> For any given element, the action may be performed at whatever time and in whatever thread the library chooses. If the action accesses shared state, it is responsible for providing the required synchronization.

### Steps To Reproduce

1. Create a micronaut app with entities in different packages
2. Specify the packages separately in a list
3. Write a basic kotest MicronautTest
4. Drop a debug in findEntities and watch how many entities are returned

### Environment Information

Jdk 11
MacOS

### Version

3.1.4

**Comment by rawilder** [comment]
I may be having a misunderstanding and some other misconfiguration, but based on code and javadocs it seems like this is potentially a bug

draft pr: https://github.com/micronaut-projects/micronaut-sql/pull/512

**Comment by MT-Jacobs** [comment]
To flatten this out a bit:
```
Collection<Class<?>> entities = new HashSet<>();
if (isClasspath()) {

    if (ArrayUtils.isNotEmpty(packages)) {
        environment.scan(Entity.class, packages).forEach(entities::add);
    } else {
        // snip
    }
}
```
becomes
```
Collection<Class<?>> entities = new HashSet<>();
if (isClasspath()) {

    if (ArrayUtils.isNotEmpty(packages)) {
        packages.parallel()
            .flatMap(pkg -> scan(Entity.class.getName(), pkg));
            .forEach(entities::add);
    } else {
        // snip
    }
}
```
That seems like a clear usage of a HashSet in a concurrent fashion to me.
