### ISSUE TITLE
Documentation on spring jdbc is out of date

### ISSUE THREAD

**Issue by viniciusxyz** [micronaut-projects/micronaut-sql#555]
### Issue description

1 - The documentation asks us to add the **io.micronaut:micronaut-spring** dependency, but it is not possible to resolve it in maven, but the following dependency is resolved and works normally **io.micronaut.spring:micronaut-spring**.

![image](https://user-images.githubusercontent.com/19265464/153321555-4008e973-298a-46da-a3ab-c6346428e4ed.png)

2- Another point is that in my tests **@Transaction** with Spring only works if the dependency *micronaut-spring-annotation* is configured in the annotation processor as in the snippet below:

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths combine.children="append">
                        <path>
                            <groupId>io.micronaut.spring</groupId>
                            <artifactId>micronaut-spring-annotation</artifactId>
                            <version>${micronaut.spring.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-Amicronaut.processing.group=${groupId}</arg>
                        <arg>-Amicronaut.processing.module=${artifactId}</arg>
                    </compilerArgs>
                </configuration>
            </plugin>

Thank you in advance for supporting this feature!

**Comment by graemerocher** [comment]
Would you like to send a PR to the documentation?

**Comment by viniciusxyz** [comment]
> Would you like to send a PR to the documentation?

I sure would like to, I just didn't send the PR because I couldn't find the doc in the repo, I'm new to the project, can you please tell me where the doc is so I can send the PR?

**Comment by viniciusxyz** [comment]
> Would you like to send a PR to the documentation?

I submitted the PR but I noticed that we have another problem on our hands, the @Transactional annotation from micronaut for spring is marked deprecated, when using it the code works perfectly, but when using the annotation from javax/jakarta or spring in if the code stops working, in the case of spring we still have the option to add the annotation process to deal with the discontinuation of the original annotation, but this requires additional configuration, is there any annotation that replaces the @Transactional of the micronaut.spring that is obsolete and does not require extra configuration?


Ps I just noticed that the link about the annotation is broken in the doc.

**Comment by viniciusxyz** [comment]
> You can just use Spring's `@Transactional` annotation not Micronaut's and as long as you have `micronaut-spring-annotation` on your annotation processor path and `micronaut-spring` on your runtime path it will work. See https://github.com/micronaut-projects/micronaut-spring/blob/ee0f40bb9af5710c1278c53b2296c56a3f4ca932/spring/src/main/java/io/micronaut/spring/tx/annotation/TransactionInterceptor.java

I added the link to the configuration process in the annotation processor path a [PR#557](https://github.com/micronaut-projects/micronaut-sql/pull/557) this should make it easier for other people who are in the process of migrating projects like me to understand.

If you have any writing or logic errors in the PR let me know and I'll fix it as soon as possible, thank you.
