### ISSUE TITLE
Question about continued support for Spring JDBC.

### ISSUE THREAD

**Issue by viniciusxyz** [micronaut-projects/micronaut-sql#556]
### Issue description

I would like to know if there are plans to deprecate the compatibility layer with Spring Jdbc in future versions, I'm asking this question because I have some applications that I plan to migrate and this feature helps a lot in this work and even maintains great performance.

If this question is in the wrong channel, I apologize in advance.

**Comment by graemerocher** [comment]
There are no plans at this stage no
