### ISSUE TITLE
Update to latest version of JOOQ

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-sql#698]
### Issue description

Since [3.17](https://www.jooq.org/notes/?version=3.17#3.17.0) baseline is Java 17. 

This relates to: [Drop 11 and 8 and set Java 17 as Micronaut 4 baseline](https://github.com/micronaut-projects/micronaut-core/issues/7006)

**Comment by wetted** [comment]
https://github.com/micronaut-projects/micronaut-sql/pull/859
