### ISSUE TITLE
Upgrade to Hibernate 6

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-sql#700]
### Issue description

https://hibernate.org/orm/releases/6.1/

**Comment by dstepanov** [comment]
The best way would be to create a hibernate6 module because not everyone is going to update to Hibernate 6 that fast. Also, Hibernate 6 doesn't support reactive compared to Hibernate 5.

**Comment by sdelamo** [comment]
@dstepanov @radovanradic Can we close this?
