### ISSUE TITLE
Support H2 version 2

### ISSUE THREAD

**Issue by kristofdho** [micronaut-projects/micronaut-sql#714]
### Feature description

Currently there is support for H2 up to version 1.4.200, but starting from 2.1.202 there have been numerous changes that seem to result in more reflective operations.

Configuration for both versions major versions could be supported based on the value of `org.h2.engine.Constants#BUILD_ID` or `org.h2.engine.Constants#VERSION_MAJOR`.

So far I've seen these changes:

This list of classes needs to be updated, because some were merged and they moved packages
https://github.com/micronaut-projects/micronaut-sql/blob/e8fde397915d74b407b64073bb189af9f4e6fc0d/jdbc/src/main/java/io/micronaut/jdbc/nativeimage/JdbcFeature.java#L85-L98

In these commits: https://github.com/h2database/h2database/commit/345e9edd0a92c80f842536a2cadfab12eaa21ea0 https://github.com/h2database/h2database/commit/d283bf763536ca54bcdf3b95538d1d19f8451db7

For my current use-case I also needed these reflective calls to be registered:
```java
@AutomaticFeature
public class H2Version2Feature implements Feature {
    private static final String[] DATA_TYPE_IMPLEMENTATIONS = {
            "org.h2.mvstore.db.LobStorageMap$BlobMeta$Type",
            "org.h2.mvstore.db.LobStorageMap$BlobReference$Type",
            "org.h2.mvstore.db.NullValueDataType",
            "org.h2.mvstore.type.ByteArrayDataType",
            "org.h2.mvstore.type.LongDataType"
    };
    private static final String[] DATA_TYPE_FACTORY_IMPLEMENTATIONS = {
            "org.h2.mvstore.tx.VersionedValueType$Factory",
            "org.h2.mvstore.db.RowDataType$Factory"
    };

    @Override
    public void beforeAnalysis(BeforeAnalysisAccess access) {
        for (String implName : DATA_TYPE_IMPLEMENTATIONS) {
            Class<?> implClass = access.findClassByName(implName);
            Field instanceField = ReflectionUtil.lookupField(implClass, "INSTANCE");
            RuntimeReflection.register(implClass);
            RuntimeReflection.register(instanceField);
        }

        for (String implName : DATA_TYPE_FACTORY_IMPLEMENTATIONS) {
            Class<?> implClass = access.findClassByName(implName);
            RuntimeReflection.register(implClass);
            RuntimeReflection.registerForReflectiveInstantiation(implClass);
        }
    }
}
```
But I'm sure that this is insufficient for full support.

These are required in `org.h2.mvstore.type.MetaType#read`: https://github.com/h2database/h2database/blob/9f08a5a7b43b3299dbe0b7cbb1f23f616e036849/h2/src/main/org/h2/mvstore/type/MetaType.java#L67

**Comment by hayond** [comment]
same issue to me, I have to add my own `AutomaticFeature ` implementation

**Comment by hayond** [comment]
> same issue to me, I have to add my own `AutomaticFeature ` implementation

ok.. seems the micironaut-data r2dbc, totally not support H2 version 2, I will revert to old version

**Comment by radovanradic** [comment]
H2 version 2.2.224 currently supported, this can be closed.

**Comment by kristofdho** [comment]
Hi @radovanradic, that's great!
Could you point me to the relevant code? The JdbcFeature class seems to be removed.

**Comment by radovanradic** [comment]
It's not needed anymore, metadata is used from shared repository so you can just build native app with H2 without JdbcFeature now.
