### ISSUE TITLE
JpaConfiguration copy operation does not copy properties and mapping resource information

### ISSUE THREAD

**Issue by tqad** [micronaut-projects/micronaut-sql#719]
Assuming that the copy method of the JpaConfiguration class should take over the values of the default configuration, there is an error in  
https://github.com/micronaut-projects/micronaut-sql/blob/d32f8fa2951a4bc1e1eb31754feea27bca26b92b/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java#L295

**Comment by radovanradic** [comment]
This is supposed to be fixed by https://github.com/micronaut-projects/micronaut-sql/pull/720
