### ISSUE TITLE
JooqConfigurationFactory (and now DSLContextFactory) no longer public

### ISSUE THREAD

**Issue by diamondq** [micronaut-projects/micronaut-sql#730]
### Expected Behavior

Since the v4.5.0 ( PR #674  ), the JooqConfigurationFactory (and as part of that PR, the broken out DSLContextFactory) was no longer marked a public class. This means that I can't use an @Replaces to override the factory.

In my case, I have multiple DSLContexts, one for each DataSource, and was using the Micrometer libraries wrapper (MetricDSLContext.withMetrics) to create a DSLContext that was reporting metrics. Because I need to use an @EachBean to build one for each DSLContext, I can't just create a single "new named" DSLContext (I'd need to dynamically rename @EachBean instance, which I don't believe is possible). Thus, without the classes being public, I can't easily handle this.

One of the greatest strengths of Micronaut and its DI framework, is the ability to customize almost all aspects to handle special uses cases. It'd be great if we could get this get these back to a public class.

### Environment Information

Micronaut SQL 4.5.0 and at least up to 4.7.0

### Version

4.7.0

**Comment by graemerocher** [comment]
we are trying to figure out how this got into a minor release. These changes were intended for the next major. Sorry about this.

**Comment by diamondq** [comment]
The fix for JooqConfigurationFactory is great. However, as part of the original PR, the DSLContextFactory was broken out of the JooqConfigurationFactory (ie. it used to be inside JooqConfigurationFactory), so that likely needs to be moved back to public as well.

**Comment by sdelamo** [comment]
> The fix for JooqConfigurationFactory is great. However, as part of the original PR, the DSLContextFactory was broken out of the JooqConfigurationFactory (ie. it used to be inside JooqConfigurationFactory), so that likely needs to be moved back to public as well.

Thanks @diamondq I have created another PR.
