### ISSUE TITLE
discontinue postgres-reactive in favor of vertx-pg-client

### ISSUE THREAD

**Issue by pjungermann** [micronaut-projects/micronaut-sql#89]
The underlying library of postgres-reactive is in maintenance mode in favor of the vertx pg-client library. The reference to its github in the docs already redirect to the vertx one (which is referencing/mentioning it).

**Comment by graemerocher** [comment]
Done https://github.com/micronaut-projects/micronaut-sql/commit/7fc60353aecc85b1a04f6ad99d0bd65c30e8ae19
