### ISSUE TITLE
[native-image] Support EntityManager generation

### ISSUE THREAD

**Issue by bufferings** [micronaut-projects/micronaut-sql#9]
Hi, I would like to know Micronaut team's opinion to send my PR.

I have 2 questions:
1. Could I send a PR with these changes?
2. Which branch should I send PR to?

I'm thinking to send pull request as a first step for native-image generation with following changes:
https://github.com/bufferings/micronaut-sql/pull/1/files

This includes 2 changes.

1. Change to use Micronaut 1.1.0
2. Change Entity scan from Environment to BeanIntrospector

The reason why I needed to use Micronaut 1.1.0 is that BeanIntrospector doesn't exist in Micronaut 1.0.4.

**Comment by graemerocher** [comment]
1. Yes please!
2. To master please

We probably want to not modify the `package-to-scan` property and maybe add an additional one that is `packages-to-use` or something. There may be cases where you still want to use package scanning.

**Comment by bufferings** [comment]
Understood! At first, I will send a PR and then will modify it to use `packages-to-use` or something.

**Comment by bufferings** [comment]
Close this issue as my questions are solved and created PR
