### ISSUE TITLE
Jasync configure interceptors

### ISSUE THREAD

**Issue by LukasPrediger** [micronaut-projects/micronaut-sql#97]
According to the [Jasync Configuration Properties](https://micronaut-projects.github.io/micronaut-sql/latest/guide/configurationreference.html#io.micronaut.configuration.jasync.JasyncPoolConfiguration) there should be a property named "interceptors" that takes a list of suppliers of QueryInterceptors in order to configure an [Interceptor](https://github.com/jasync-sql/jasync-sql/wiki/Interceptors) to Jasync.

I haven't found any documentation on how to pass a class into a property as YAML. I was also unable to inject and change the configuration in order to register the interceptor manually.

What is the correct way to do this and might it be a good idea to have MicronautSQL register Interceptors automatically via injection?

**Comment by sdelamo** [comment]
Closed via https://github.com/micronaut-projects/micronaut-sql/pull/266
